# Generated by Django 5.2.7 on 2025-12-18 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_adoptionrequest_owned_pet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownedpet',
            old_name='is_listed_for_adoption',
            new_name='is_available',
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='adopter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ownedpet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_pets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ownedpet',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='core.pet'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
