# Generated by Django 5.2.7 on 2025-12-23 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_is_listed_for_adoption_ownedpet_is_available_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownedpet',
            old_name='is_available',
            new_name='is_listed_for_adoption',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='message',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='owned_pet',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='status',
        ),
        migrations.AlterField(
            model_name='ownedpet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ownedpet',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pet'),
        ),
    ]
