# Generated by Django 5.2.7 on 2025-12-30 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_chatroom_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
