# Generated by Django 5.2.7 on 2025-12-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_pet',
            field=models.BooleanField(default=False),
        ),
    ]
